services:
  - type: web
    name: smart-nutrition-api
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && gunicorn src.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20
      - key: SECRET_KEY
        generateValue: true
